### ISSUE TITLE
Seg fault on Guerrero Negro with Full output mode

### ISSUE THREAD

**Issue by danknights** [GabeAl/NINJA-OPS#11]
This command runs:

ninja.py -i seqs.fna -o ninja4 -R

But this fails:
ninja.py -i seqs.fna -o ninja4 -R -F 

On this input file:
https://github.com/danknights/mice8992-2016/raw/master/data/guerreronegro/seqs.fna

**Comment by GabeAl** [comment]
No failure here. Send me the log and system, ninja version, and console output of failures and I'll take a look!
