### ISSUE TITLE
UNSUPPORTED_MAPPING

### ISSUE THREAD

**Issue by ZeweiSong** [GabeAl/NINJA-OPS#18]
Hi, Gabe

I got "UNSUPPORTED_MAPPING" on my taxonomy column when using NINJA in my Ubuntu virtual machine, but the same setting ran fine of MSI (I use the exact same database).

Any idea? Thanks!

Zewei

**Comment by ZeweiSong** [comment]
Never mind, I think I still used a wrong database! I forgot to change the long label to short name in my FASTA file.

**Comment by GabeAl** [comment]
Glad it worked!

Also, these tools should work on WSL on Windows now (if you have updated to
the Creator's update of Windows 10), so no need for a virtual machine!

Cheers,
Gabe

**Comment by ZeweiSong** [comment]
Tried it on Windows today, got this error:

Segmentation fault (core dumped)

Traceback (most recent call last):
  File "/mnt/e/GoogleDrive/Research/Tools/ninja-ops/bin/ninja.py", line 609, in <module>
    main(p)
  File "/mnt/e/GoogleDrive/Research/Tools/ninja-ops/bin/ninja.py", line 587, in main
    logger.log("NINJA-OPS parse time: " + str(t3.timeit(1)) + "\n")
  File "/home/zewei/anaconda3/lib/python3.6/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/mnt/e/GoogleDrive/Research/Tools/ninja-ops/bin/ninja.py", line 585, in <lambda>
    logger, legacy_table, run_with_shell=run_with_shell, print_only=args['print_only'])
  File "/mnt/e/GoogleDrive/Research/Tools/ninja-ops/bin/ninja.py", line 427, in ninja_parse
    raise ValueError("ERROR: Parsing failed. Exiting.")
ValueError: ERROR: Parsing failed. Exiting.

Is it because I am using Python 3.6?

**Comment by GabeAl** [comment]
Just tried it on 2 windows machines here:

> gabe@DCanyon:/mnt/c/Users/Gabe/Desktop/embalmer/reflateN$ ninja.py -i
> uBiome/bad_noFlash/combined_seqs.fna -o tryme
> NINJA-OPS v1.5.1
> NINJA-OPS database directory is
> /mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/databases/greengenes97
> Running NINJA-OPS filter...
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/bin/ninja_filter_linux"
> "uBiome/bad_noFlash/combined_seqs.fna"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/ninja"   D 1
> Not using paired-end reads
> Performing NINJA replicon-denoising at 1 compacted reads.
> WARNING: Found 32 sequences with ambiguity (105 ambiguous bases).
> Number of sequences: 86604
> Total reads considered: 86572
> Reads sorted.
> 2 Samples found.
> Finished.
> NINJA-OPS filter time: 0.09263800014741719
> Running Bowtie2...
> bowtie2-align-s --no-head -x
> /mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/databases/greengenes97/greengenes97
> -S "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/alignments.txt" --np
> 0 --mp "1,1" --rdg "0,1" --rfg "0,1" --score-min
> "L,0,-0.030000000000000027" --norc -f
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/ninja_filt.fa" -p 8
> --very-sensitive
>
> Bowtie time: 2.9872389999218285
> Running NINJA-OPS compact...
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/bin/ninja_compact_linux"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/alignments_uncompacted.txt"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/databases/greengenes97/greengenes97.tcf"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/alignments.txt"
> Done.
> NINJA-OPS compact time: 0.3699719998985529
> Running NINJA-OPS parse...
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/bin/ninja_parse_filtered_linux"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/ninja"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/alignments.txt"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/databases/greengenes97/greengenes97.db"
> "/mnt/c/Users/Gabe/Desktop/embalmer/reflateN/NINJA-OPS-1.5.1/databases/greengenes97/greengenes97.taxonomy"
> Opened
> /mnt/c/Users/Gabe/Desktop/embalmer/reflateN/tryme/ninja_otutable.biom for
> OTU Table writing
> Total OTUs available to pick from: 99322
> Number of unique samples: 2, max reads: 29884
> Total chimeric alignments: 0
> Total reads expanded: 38688
> Run complete.
> NINJA-OPS parse time: 0.08933900017291307
> gabe@DCanyon:/mnt/c/Users/Gabe/Desktop/embalmer/reflateN$
>

Here's how I did a clean setup:
wget https://github.com/GabeAl/NINJA-OPS/archive/v1.5.1.zip
unzip v1.5.1.zip
cd NINJA-OPS-1.5.1/bin
wget
https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.3/bowtie2-2.3.3-linux-x86_64.zip/download
-O bt2.zip
unzip bt2.zip
mv bowtie2-2.3.3/bowtie2-align-s .
PATH=$PATH:$(pwd)

#To test:
cd /somewhere/else/with/data
ninja.py -i combined_seqs.fna -o tryme

You can clean up the unnecessary intermediates (the zip files, the bowtie2
directory that got extracted, etc) and add the ninja-ops bin directory to
your PATH in your ~/.bashrc to have it always runnable.

If this doesn't work, to debug your setup, I'll need to know the following:
1. What input file are you using?
2. Is NINJA-OPS in your PATH? (do `echo $PATH` and make sure you see the
NINJA-OPS bin in there)
3. What version of NINJA-OPS is this? (Only v1.5.1 is supported! Check with
`ninja.py --version`)
4. What version of Windows 10 are you using? (Check in cmd -- not the BASH
shell, but a new cmd prompt in Windows -- with `ver` . Only Microsoft
Windows [Version 10.0.15063] and later are supported)

Let me know!
Gabe
