### ISSUE TITLE
Need to support spaces in file names in python wrapper

### ISSUE THREAD

**Issue by danknights** [GabeAl/NINJA-OPS#2]

**Comment by GabeAl** [comment]
This seems to be fixed? Works in Windows with a couple of tests.

**Comment by bhillmann** [comment]
I thought the issue was on Macs?

**Comment by bhillmann** [comment]
Check out the pull request #1

**Comment by danknights** [comment]
FYI I fixed the white space issue last week.

Dan

## 

Dan Knights, PhD
Assistant Professor
BioTechnology Institute, Computer Science and Engineering
University of Minnesota
http://www.knightslab.org
cell: 510-900-9015 (dials backwards)
office: MEMORIZE-PI (636-674-9374)
lab: 612-5-MICROB (612-564-2762)

**Comment by bhillmann** [comment]
Nice, looks good!
