### ISSUE TITLE
Need improved documentation for generating custom databases

### ISSUE THREAD

**Issue by danknights** [GabeAl/NINJA-OPS#5]
Docs should explain precisely the format for inputs to ninja_prep, and the usage of ninja_prep.

**Comment by GabeAl** [comment]
Thanks! See if the latest commit fixes this. I added a blurb to the README. Since I'm not too familiar with markdown, feel free to tweak spacing etc.

**Comment by danknights** [comment]
Thanks! Looks good. Might want to say a word about the taxonomy file in the
new DB section.

Also would you mind updated the binaries? You make the best binaries for
all platforms.

Dan

## 

Dan Knights, PhD
Assistant Professor
BioTechnology Institute, Computer Science and Engineering
University of Minnesota
http://www.knightslab.org
cell: 510-900-9015 (dials backwards)
office: MEMORIZE-PI (636-674-9374)
lab: 612-5-MICROB (612-564-2762)
